### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by mkleczek** [mmhelloworld/idris-jvm#108]
First of all - thanks for the great work.

I am trying to build idris-jvm from source. Idris version built from current master.
From the root directory issuing _mvn install_. The build fails on idris-jvm-server complaining it cannot find export packages:

`SAltDeserializer.java:[3,28] package IdrisJvm.Core.export does not exist`

Could you provide some hints on how to build idris-jvm from source?

**Comment by mmhelloworld** [comment]
Hi,

Thank you for trying out idris-jvm. Do you have the latest release from [here](https://github.com/mmhelloworld/idris-jvm/releases)? And do you see any errors in `<idris-jvm.zip extracted dir>/codegen/idris-jvm-server.log`?

**Comment by mkleczek** [comment]
Seems I've missed that idris-jvm is self-hosted and needs a bootstrap. After installing the bootstrap and setting IDRIS_JVM_HOME properly it worked.
Thanks!
