### ISSUE TITLE
Add an option to compile Idris JVM output to class files without packaging into JAR with runtime

### ISSUE THREAD

**Issue by ivanmoreau** [mmhelloworld/idris-jvm#159]
Currently, when compiling Idris code to the JVM backend, the output is automatically packaged into a JAR file along with the necessary runtime files. However, there seems to be no option in the `idris2 --help` parameter to compile Idris code to the JVM backend and generate only the class files, without automatically packaging them into a JAR file with the runtime.

This missing feature can be problematic for users who want to integrate Idris code with existing Java projects or who want to manually package the class files in their preferred way. It would be beneficial to add an option to compile Idris JVM output into just the class files, without automatically zipping them into a JAR file with the runtime.

Therefore, it would be great if an option were added to the idris2 command-line tool that allows users to specify whether they want the output to be compiled only to class files, without automatically packaging them into a JAR file with the runtime.

Can this feature be implemented? Thank you!

**Comment by mmhelloworld** [comment]
Hi,

I agree. We can just produce class files. I think we don't even have to provide an option to create JAR and let the users package themselves as usually that will be done with a build tool potentially along with other dependencies. I will look into this.

**Comment by mmhelloworld** [comment]
Hello,

With the [latest release](https://github.com/mmhelloworld/idris-jvm/releases/tag/latest), Idris JVM compiler would produce class files instead of jar. Please try it out and let me know for any issues.
