### ISSUE TITLE
Why do I get a failed connection? it was working yesterday.

### ISSUE THREAD

**Issue by PhilAndrew** [mmhelloworld/idris-jvm#17]
$ ./compile.sh
idris-codegen-jvm: FailedConnectionException2 "localhost" 62184 False connect: failed (Connection refused (WSAECONNREFUSED))
FAILURE: "idris-codegen-jvm" [".\\pythag.ibc","-o","pythag"]

**Comment by mmhelloworld** [comment]
Hi,

Did you run `bin/setup` as mentioned under the [install](https://github.com/mmhelloworld/idris-jvm#install) section? It tries to connect to the bytecode assembler server which is not running. If you run the setup script, the script starts the assembler server.

**Comment by PhilAndrew** [comment]
Ok after running setup it runs, so I should to run setup each day after I started up my machine?

**Comment by mmhelloworld** [comment]
When you compile something, it would try to connect to the assembler so basically before compilation, it should be running.

**Comment by PhilAndrew** [comment]
Ok good thanks. Can you also tell me, lets say I have many idr files in directories and sub-directories, how can I compile those to generate the class files? I don't have any main idr file, just I want the idr files to produce class files which I will then use from Scala.

How can this be done? Should it be using ipkg ? Foo.ipkg eg http://stackoverflow.com/questions/29054735/generate-library-instead-of-executable-in-idris

**Comment by mmhelloworld** [comment]
The basic idea is that you need to have export definitions to be able to use it from Scala and you would still need to have a `Main` module along with exports of its own but its main function can be just `main = pure ()`. Then you could do,

`idrisjvm Main.idr Foo.idr -o target`

I will post an example shortly.

**Comment by mmhelloworld** [comment]
Sorry, it took me longer than I expected as I had to add an option to make this easier. I have added an example for this in [faq.md](https://github.com/mmhelloworld/idris-jvm/blob/master/docs/faq.md). Please let me know if you have any more questions. By the way, I have also created a [gitter room](https://gitter.im/mmhelloworld/idris-jvm) for idris-jvm if you would like to use gitter for any questions or feedback.

**Comment by PhilAndrew** [comment]
Thanks! have it able to compile at the moment.

**Comment by mmhelloworld** [comment]
Great, I am closing this issue.
