### ISSUE TITLE
[Question] about primitive types

### ISSUE THREAD

**Issue by zjhmale** [mmhelloworld/idris-jvm#3]
readme says that `This is still work in progress so only basic primitive types (No BigIntegers, doubles) are supported at the moment.`

but through [this](https://github.com/mmhelloworld/idris-jvm/blob/master/runtime/IdrisJvm/FFI.idr#L32-L37) definition, i agree with the biginteger part, but we already get double right?

**Comment by mmhelloworld** [comment]
Hi,

Though [FFI.idr](https://github.com/mmhelloworld/idris-jvm/blob/master/runtime/IdrisJvm/FFI.idr#L32-L37) declares `Double`, the code generator currently doesn't do anything with it. If you look at the code generator [here](https://github.com/mmhelloworld/idris-jvm/blob/master/src/IdrisJvm/CodegenJvm.hs#L663-L686), it only handles `ATInt` and not `ATFloat`.

**Comment by zjhmale** [comment]
fire enough, thx! i just start walking through the codebase.
