### ISSUE TITLE
idris on the browser?

### ISSUE THREAD

**Issue by viebel** [mmhelloworld/idris-jvm#30]
So cool that you were able to make idris on the jvm!!!

If you can make it on javascript, we will be able to run idris in the browser and it will be great for educational purposes. We could have interactive tutorial about idris like this [scheme tutorial](http://blog.klipse.tech/scheme/2016/09/11/scheme-tutorial-1.html).

**Comment by mmhelloworld** [comment]
Hi,

Thank you!

JavaScript backend is already supported by Idris itself. Please see here: https://github.com/idris-lang/Idris-dev/blob/master/docs/reference/codegen.rst.

**Comment by viebel** [comment]
And now the 1.000.000 dollars question:
Is it possible to have an Idris evaluator in javascript i.e. to have javascript code that knows to evaluate Idris code?

**Comment by mmhelloworld** [comment]
I am not sure as I haven't used JavaScript back end.

**Comment by viebel** [comment]
Can Idris evaluates itself?

**Comment by bamboo** [comment]
@viebel I think I recall someone reporting to have successfully compiled Idris with GHCJS.

**Comment by viebel** [comment]
wow that's amazing @bamboo. But I need more details about it...

**Comment by bamboo** [comment]
@viebel this might help - https://github.com/idris-lang/Idris-dev/pull/3436

**Comment by viebel** [comment]
thx @bamboo

**Comment by mmhelloworld** [comment]
That is really cool. Thanks @bamboo for the link.
