### ISSUE TITLE
Interop with other Java libraries

### ISSUE THREAD

**Issue by fikse** [mmhelloworld/idris-jvm#31]
How do you import third party Java libs and use them?

**Comment by mmhelloworld** [comment]
Hi,

As Idris JVM generates bytecode directly, we don't have to care about (importing) Java libraries during compilation. We just need to have FFI declarations and compile. Then only at runtime, we should provide all the Java dependency libararies.

Here is an example of using `guava` library:
**guava.idr**:
```idris
module Main

import IdrisJvm.IO
import Java.Lang
import Java.Util

namespace Joiner

  JoinerClass : JVM_NativeTy
  JoinerClass = Class "com/google/common/base/Joiner"

  Joiner : Type
  Joiner = JVM_Native JoinerClass

  on : String -> JVM_IO Joiner
  on = invokeStatic JoinerClass "on" (String -> JVM_IO Joiner)

main : JVM_IO ()
main = printLn $ Objects.toString !(Joiner.on ",")
```

#### Compile
Here note that we don't mention anything about guava jar:
`idrisjvm guava.idr -o target`

#### Run
Here we provide all the dependency jars. Of course, we could use build tools to make this easier.
```
$ java -cp target:/path/to/.idrisjvm/idris-jvm-runtime-1.0-SNAPSHOT.jar:/path/to/guava-20.0.jar main.Main
"com.google.common.base.Joiner@5f184fc6"
```

**Comment by fikse** [comment]
That is actually really nice! Thanks for explaining.
