### ISSUE TITLE
Cannot run compiled program

### ISSUE THREAD

**Issue by Supernerd11** [mmhelloworld/idris-jvm#41]
I have tried to compile an idris program, even the pythag example in the README, but i get an error. I tried to build it myself, but the tests fail with the same error.
The error is: 
```
Exception in thread "main" java.lang.NoSuchMethodError: main.Main._lbrace_runMain0_rbrace_()Ljava/lang/Object;
	at main.Main.main(Unknown Source)
```

**Comment by mmhelloworld** [comment]
Hi,

It looks like you are using the latest Idris. In the latest version `{runMain0}` is `{runMain_0}` hence it is failing with that error. Could you use Idris 0.99.1? 
I am working on supporting the latest version. I have one test failing which hopefully I will get it fixed and upload the new backend jar in few hours.

Thanks for trying out Idris JVM backend!

**Comment by Supernerd11** [comment]
I'll try Idris 0.99.1 when I get home. Thanks for the quick response.

**Comment by Supernerd11** [comment]
I got it working.

**Comment by mmhelloworld** [comment]
Great! I also got the latest Idris version working. I will upload the new backend shortly.
