### ISSUE TITLE
Interface support

### ISSUE THREAD

**Issue by Supernerd11** [mmhelloworld/idris-jvm#42]
Hi, I'm trying to make a simple Swing binding to idris, but i want to make sure that a class implements a specific interface. Is that possible?

**Comment by mmhelloworld** [comment]
Hi,

Yes, it is possible. Here is an example:

```idris
exports : FFI_Export FFI_JVM "hello/IdrisThread extends java/lang/Thread implements java/lang/Runnable" []
exports1 =
  Fun idrisThreadConstructor Constructor $
  Fun idrisThreadWithNameConstructor Constructor $
  Fun run ExportDefault $
  Fun getThreadName (Super "getName") $
  End
```

The above export section creates a class called `IdrisThread` which extends Java `Thread` class and implements `Runnable`. In the exported class as you can see, it exports two Idris functions (`idrisThreadConstructor` and `idrisThreadWithNameConstructor`) as constructors, `run` function exported with the same name for Java which becomes the implementation for `run` method and the last declaration `getThreadName` calls super class method `getName`. The complete example is [here](https://github.com/mmhelloworld/idris-jvm/blob/master/idris-jvm-integration-test/src/test/resources/idris-test-sources/ffi/ffi.idr#L221).

**Comment by Supernerd11** [comment]
I meant when "importing" a class, not exporting. I noticed the exporting when looking at the FFI examples.

**Comment by mmhelloworld** [comment]
Sorry, I misunderstood. Do you mean to make sure in Idris that a Java class implements some interface? If yes, that is not possible as there is no concept of Java class files during Idris compilation so a Java class file cannot be inspected. This is a good thing as otherwise we have to introduce the concept of classpath for the code generation and would involve loading classes for inspection during compilation.

**Comment by Supernerd11** [comment]
Well, I mean more that i have to specify what interfaces it implements, like with Inherits.

**Comment by mmhelloworld** [comment]
Closing this now as the answer is to use `Inherits` to specify what a class inherits. Please reopen if you have more questions.
