### ISSUE TITLE
Lambdas in ffi?

### ISSUE THREAD

**Issue by Supernerd11** [mmhelloworld/idris-jvm#43]
Can i use an anonymous function/lambda as an argument to a method?

**Comment by mmhelloworld** [comment]
It is not possible at the moment but I think we can support it. We will keep this issue open to track the support for it. For now, you can pass an instance of the target interface obviously.

**Comment by mmhelloworld** [comment]
Hi,

Java lambdas are now supported in FFI. Idris functions can be passed as Java lambdas in FFI. Here is an example:

```idris
main : JVM_IO ()
main = ArrayList.fromList ["foobar", "hello", "world"] >>=
       stream >>=                                           -- Java 8 Stream from Java's ArrayList
       filter (jlambda (not . isPrefixOf "foo")) >>=        -- Idris function as Java "Predicate" lambda
       map (jlambda Strings.reverse) >>=                    -- Idris function as Java "Function" lambda
       collect !toList >>=
       Objects.toString >>=
       printLn
```
