### ISSUE TITLE
Cannot run install script

### ISSUE THREAD

**Issue by srctxt** [mmhelloworld/idris-jvm#61]
hi,
Impressive project which I very much like to try out. Sadly something goes wrong with the install script on my macbook.

Version: idris-jvm-1.0-SNAPSHOT-20170704.zip

System:
     $ java -version
     java version "1.8.0_121"
     $ idris --version
     1.1.1

Error:
./idris-jvm/bin/install 
./IdrisJvm/Effects.idr:18:5:
Effects.IdrisJvm.Effects.System, JVM_IO implementation of Effects.Handler, method handle is not total as there are missing cases due to Effects.IdrisJvm.Effects.System, JVM_IO implementation of Effects.Handler, method handle
./IdrisJvm/Effects.idr:18:5:Could not build: Effects.IdrisJvm.Effects.System, JVM_IO implementation of Effects.Handler, method handle is not total as there are missing cases due to Effects.IdrisJvm.Effects.System, JVM_IO implementation of Effects.Handler, method handle

**Comment by mmhelloworld** [comment]
Hi,

Thank you for trying out `idris-jvm`. It seems like you are running with latest Idris (1.1.1?) that has some additional functions for `System` effect and hence it is complaining about it. `idris-jvm` release that is currently available is for Idris 1.0. I will release a new version for Idris 1.1.1 shortly.

**Comment by mmhelloworld** [comment]
I have uploaded a new release for Idris 1.1.1. Please try it out and let me know if you have any issues.
