### ISSUE TITLE
Typer provider realized by idris-jvm

### ISSUE THREAD

**Issue by esscue23** [mmhelloworld/idris-jvm#65]
Hi Marimuthu,

great project you are working on! I played a bit with it and I'm quite impressed how smooth it works. 

I was wondering if you are planning to extend idris-jvm such that one can realize type providers with it? I would like to write a type provider making use of an existing java library.

I created a small example:
```
strToType : String -> Type
strToType "Integer" = Int
strToType _         = String

fromConsole : JVM_IO (Provider Type)
fromConsole =
  do str <- getLine
     pure (Provide (strToType str))

%language TypeProviders

%provide (T1 : Type) with fromConsole

two : T1
two = 2
```

The example reads during compilation a string. Type checking fails unless the user enters "Integer". The example works with "fromConsole" having a type of "IO (Provider Type)", but not with "JVM_IO (Provider Type)".

**Comment by mmhelloworld** [comment]
Hi @esscue23,

Thank you for trying out idris-jvm and for your kind words. As you noticed, it is not possible for type providers to be in `JVM_IO` but since we have `IO`, we can, of course, launch any process (including JVM or any build tool like Maven that takes care of classpath) in it and provide types based on the execution of that process.

For example, the following program compiles only when the Java class `helloworld.HelloWorld` outputs "Integer".

```idris
module Main

import IdrisJvm.IO
import System

%dynamic "libc"

%language TypeProviders

strToType : String -> Type
strToType "Integer" = Int
strToType _         = String

jvmProvider : IO (Provider Type)
jvmProvider = do
  system "java -cp path/to/classes helloworld.HelloWorld > jvmout.txt"
  Right str <- readFile "jvmout.txt"
  pure . Provide . strToType $ trim str

%provide (JvmOutType : Type) with jvmProvider

foo : JvmOutType
foo = 23

main : JVM_IO ()
main = printLn foo

```

**Comment by esscue23** [comment]
Hi Marimuthu,

thank you for the quick reply. I've also considered the option you are describing. The only issue is that the java API I want to use is quite complex. Therefore, it would have been nice to directly use Java FFI calls to access the API in the type provider. But of course this requires the compiler to not only know how to generate jvm code, but also how to execute it. I guess this is not so easy to implement...

**Comment by nightscape** [comment]
Could this maybe help?
https://hackage.haskell.org/package/inline-java

**Comment by esscue23** [comment]
Exactly, having something similar available for an Idris type provider would be great! Is there a way to directly use Haskell libraries in Idris?

**Comment by mmhelloworld** [comment]
Closing this old issue as the focus is now on Idris 2. With Idris 2, we can now run direct `IO` actions on the JVM as the compiler itself can run on the JVM but there is no type providers yet in Idris 2.
