### ISSUE TITLE
Support for generics?

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [mmhelloworld/idris-jvm#71]
Is there a way to support java generics?

**Comment by mmhelloworld** [comment]
Can you please add some description? What do you mean by generics? Java generics?

**Comment by Supernerd11** [comment]
yes

**Comment by mmhelloworld** [comment]
Since JVM doesn't really differentiate between `List<String>` and `List<Integer>` and this repository being JVM backend, supporting Java generics with all its variances would be out of scope without much benefit, and also considering interop with other languages as well on the JVM.
