### ISSUE TITLE
Idris compiler gets in the way of (J)Float

### ISSUE THREAD

**Issue by alaendle** [mmhelloworld/idris-jvm#85]
If the code uses a FLoat but never decomposes it the idris compiler creates a deconstructor with arity 0.

```
["IdrisJvm.FFI.Float", {
				"DConstructor": ["IdrisJvm.FFI.Float", 0, 0]
			}],
```

From the perspective of the compiler this is correct - since from its perspective no one ever needs to decompose this value to get the underlying double. But the jvm runtime does so...

```
java.lang.IllegalArgumentException: Unable to convert value IdrisObject{constructorId=0, property0=null, property1=null, property2=null, property3=null, property4=null, property5=null, property6=null, property7=null, property8=null, property9=null, properties=null} of type (class io.github.mmhelloworld.idrisjvm.runtime.IdrisObject) to float
	at io.github.mmhelloworld.idrisjvm.runtime.Util.toFloat(Util.java:170)
	at main.Main.$lbraceAPPLY_0$rbrace(Main.idr)
	at main.Main.lambda$call__IO$2(Main.idr)
	at io.github.mmhelloworld.idrisjvm.runtime.Runtime.unwrap(Runtime.java:186)
```

The simplest possible workaround - just add a something that decomposes a float anywhere - it never needs to be executed; just need to be present at compile time so that idris recognizes the arity of float.

I don't know if this can be handled in the backend compiler; otherwise I guess a issue should be created on the main compiler - so that it is somehow possible to indicate things that couldn't be erased during compilation.

**Comment by mmhelloworld** [comment]
JVM back end shouldn't be trying to convert an `IdrisObject` to `float`. Could you give  a simple example that reproduces this problem?

**Comment by alaendle** [comment]
Nothing simpler than that - please excuse the missing reproduction case on my first post - I thought the problem is obvious ;-)

```
module Main

import IdrisJvm.FFI
import IdrisJvm.IO
import Effect.Random
import Effect.System
import IdrisJvm.Effects
import Effects

%access public export

IdrisFloatClass : JVM_NativeTy
IdrisFloatClass = Class "java/lang/Float"

isInfinite : JFloat -> JVM_IO Bool
isInfinite = invokeStatic IdrisFloatClass "isInfinite" (JFloat -> JVM_IO Bool)

main : JVM_IO ()
main = do
  b <- isInfinite $ Float 42.0
  printLn $ show b
```

This small sample should throw the mentioned excepetion during runtime.

**Comment by mmhelloworld** [comment]
Thank you. That makes it really clear. I am looking into it.

**Comment by mmhelloworld** [comment]
If I add the following line with an import for `Java.Lang`, then the program works. There is a test with this line which also apparently works.

`printLn $ maxFloat (Float 3.2) (Float 5.5)`

**Comment by alaendle** [comment]
For sure - that's exactly what I've tried to say with a description of a possible workaround; in your case `printLn` triggers the decomposition via...
```
Show JFloat where
show (Float d) = show d
```
And this is visible to the idris compiler - so it knows that the value of d matters. But in my example the compiler has no indication that the double value matters - so it's erased - at least this is my interpretation (as I doubt that I am able to I understand the inner workings of the Idris compiler!).

**Comment by alaendle** [comment]
I haven't tried this yet, but maybe just a `%used Float d` annotation might be enough?

**Comment by mmhelloworld** [comment]
That is the fix :) I will push a new release with that fix. Thank you for your help.
