### ISSUE TITLE
Problematic behaviour of Idris TypeProviders

### ISSUE THREAD

**Issue by alaendle** [mmhelloworld/idris-jvm#91]
I guess this is a problem inside Idris itself - however since I noticed it while using the JVM TypeProvider I report it here - at least to track it's progress or be aware of this limitation.

```
module Main

import IdrisJvm.JvmImport
import Effect.System -- <-- this line is problematic

%access public export

%language TypeProviders
%language ElabReflection

objectsClass : String
objectsClass = "java/util/Objects"

jdkimport [
    (objectsClass, ["toString"])
]

main : IO ()
main = pure ()
```

... produces the error message...

> Multiple definitions found for System.getEnv

However

```
module Main

import Effect.System
import System

%access public export

main : IO ()
main = do
  printLn !(System.getEnv "dfasd")
```

works fine if compiled/executed. But when we try to execute this in the REPL we also get the error.

> Multiple definitions found for System.getEnv

So I believe this is more a problem in idris itself. However it only gets annoying in the context of typeproviders, sine it effectively prohibits the use of typeproviders and the effect system in one idris file.

**Comment by mmhelloworld** [comment]
Closing this old issue as the focus is now on Idris 2 and with that, we have a completely new FFI.
