### ISSUE TITLE
Error with install on Windows

### ISSUE THREAD

**Issue by watashiwa-toki** [mmhelloworld/idris-jvm#96]
Idris 1.3.1 (precompiled binary with FFI support), Java 8, C:\Idris;C:\Idris\mingw\bin in system PATH variable.

![error](https://user-images.githubusercontent.com/33194329/54084617-85f9a880-4365-11e9-876c-b5e1cec9b519.png)

**Comment by mmhelloworld** [comment]
Thank you for trying out idris-jvm. I will look into this issue.

**Comment by mmhelloworld** [comment]
Hi,

This should be fixed now. Please try it again and reopen this issue if you still have issues.

**Comment by watashiwa-toki** [comment]
Everything works fine, thanks! Is it possible to use java code with JNI
(java + inline assembler, for example) instead of pure java in idris ffi?

вс, 26 мая 2019 г., 21:51 Marimuthu Madasamy <notifications@github.com>:

**Comment by mmhelloworld** [comment]
Thank you for confirming that the fix works. Native methods are not supported yet. It looks like we need to support `static` blocks to load native libraries and a way to declare native methods in the exported classes from Idris. I will create an issue for this.
