### ISSUE TITLE
RawSystem

### ISSUE THREAD

**Issue by Chalolennox** [mmhelloworld/idris-jvm#98]
Hi,
I tried to complie the example on windows and i get the following error message:

C:\idris\examples>idris --portable-codegen jvm.bat pythag.idr -o target

idris-codegen-jvm.bat: rawSystem: does not exist (No such file or directory)

**Comment by Chalolennox** [comment]
this issue is already solved

**Comment by Chalolennox** [comment]
I don't know how to solve this on windows 10

**Comment by Chalolennox** [comment]
my bad

**Comment by g-pechorin** [comment]
How was this solved?

**Comment by Chalolennox** [comment]
I just added .bat to the jvm call
________________________________
Von: Peter LaValle <notifications@github.com>
Gesendet: Freitag, 19. April 2019 15:09
An: mmhelloworld/idris-jvm
Cc: Chalolennox; State change
Betreff: Re: [mmhelloworld/idris-jvm] RawSystem (#98)


How was this solved?
